---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: helloworld
  name: helloworld
spec:
  containers:
    - image: "mcr.microsoft.com/acc/samples/aks/helloworld:1.7"
      command:
        - python3
        - main.py
      imagePullPolicy: Always
      name: helloworld
      ports:
        - containerPort: 80
        - containerPort: 443
  runtimeClassName: kata-cc-isolation
