---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: helloworld
  name: helloworld
spec:
  containers:
    - image: "mcr.microsoft.com/acc/samples/aks/helloworld:1.8"
      command:
        - python3
        - main.py
      imagePullPolicy: Always
      name: helloworld
      ports:
        - containerPort: 80
        - containerPort: 443
      readinessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 5
        failureThreshold: 3
  runtimeClassName: kata-cc-isolation
