# --------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# --------------------------------------------------------------------------------------------
---
apiVersion: v1
kind: Pod
metadata:
  name: kafka-producer
  labels:
    azure.workload.identity/use: "true"
spec:
  serviceAccountName: workload-identity-sa
  containers:
    - image: $PRODUCER_IMAGE
      name: kafka-producer
      command:
        - /produce
      env:
        - name: MSG
          value: "Azure Confidential Computing"
        - name: PUBKEY
          value: |-
            $PUBKEY
        - name: EVENTHUB_NAMESPACE
          value: $EVENTHUB_NAMESPACE
        - name: EVENTHUB
          value: $EVENTHUB
        - name: LOG_FILE
          value: $LOG_FILE
      resources:
        limits:
          cpu: 200m
