---
apiVersion: v1
kind: Pod
metadata:
  name: kafka-golang-consumer
  labels:
    azure.workload.identity/use: "true"
    app.kubernetes.io/name: kafka-golang-consumer
spec:
  serviceAccountName: workload-identity-sa
  runtimeClassName: kata-cc-isolation
  containers:
    - image: $SIDECAR_IMAGE
      imagePullPolicy: Always
      name: skr
      env:
        - name: SkrSideCarArgs
          value: ewogICAgImNlcnRjYWNoZSI6IHsKCQkiZW5kcG9pbnRfdHlwZSI6ICJMb2NhbFRISU0iLAoJCSJlbmRwb2ludCI6ICIxNjkuMjU0LjE2OS4yNTQvbWV0YWRhdGEvVEhJTS9hbWQvY2VydGlmaWNhdGlvbiIKCX0gIAp9
        - name: LogLevel # enable for debugging SKR
          value: debug
      command:
        - /bin/sh
        - -c
        - /skr.sh
      volumeMounts:
        - mountPath: /opt/confidential-containers/share/kata-containers/reference-info-base64
          name: endor-loc
    - image: $CONSUMER_IMAGE
      imagePullPolicy: Always
      name: kafka-golang-consumer
      env:
        - name: SkrClientKID
          value: $SkrClientKID
        - name: SkrClientMAAEndpoint
          value: $MAA_ENDPOINT
        - name: SkrClientAKVEndpoint
          value: $AZURE_AKV_RESOURCE_ENDPOINT
        - name: EVENTHUB_NAMESPACE
          value: $EVENTHUB_NAMESPACE
        - name: EVENTHUB
          value: $EVENTHUB
        - name: SOURCE
          value: $SOURCE_ID
        - name: LOG_FILE
          value: $LOG_FILE
      command:
        - /consume
      ports:
        - containerPort: 3333
          name: kafka-consumer
      resources:
        limits:
          memory: 1Gi
          cpu: 200m
  volumes:
    - name: endor-loc
      hostPath:
        path: /opt/confidential-containers/share/kata-containers/reference-info-base64
---
apiVersion: v1
kind: Service
metadata:
  name: consumer
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: kafka-golang-consumer
  ports:
    - protocol: TCP
      port: 80
      targetPort: kafka-consumer