name: Push Image

on:
  workflow_call:
    inputs:
      repo_type:
        description: "Azure Container Registry to push the image to"
        required: true
        type: string
      image:
        description: "Image to push"
        required: true
        type: string
      tag:
        description: "Tag to push the image with"
        required: true
        type: string
      docker_context:
        description: "Docker Context to Use"
        required: true
        type: string
      dockerfile_path:
        description: "Docker File Path"
        required: true
        type: string

permissions:
  id-token: write
  contents: read
  attestations: write
  packages: write

jobs:
  push-example-image:
    name: Push Image (${{ inputs.image }})
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      # needed to avoid a bug where imageId and digest output are the same
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0
        with:
          version: v0.18.0

      - name: Download ORAS CLI
        uses: oras-project/setup-oras@22ce207df3b08e061f537244349aac6ae1d214f6 # v1.2.4

      - name: Log into Azure
        uses: azure/login@7184910d9eb2b1c5e48f7073824a90609bb9b6d6 # v2.3.1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set Azure Registry
        run: |
          echo "AZURE_REG_NAME=${{ inputs.repo_type == 'public' && secrets.AZURE_REGISTRY_NAME || inputs.repo_type == 'private' && secrets.TEST_AZURE_REGISTRY_NAME }}" >> $GITHUB_ENV
          echo "AZURE_REG_URL=${{ inputs.repo_type == 'public' && secrets.AZURE_REGISTRY_URL || inputs.repo_type == 'private' && secrets.TEST_AZURE_REGISTRY_URL }}" >> $GITHUB_ENV

      - name: Log in to Azure Container Registry
        run: az acr login --name $AZURE_REG_NAME

      - name: Build and Push Docker Image
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # v5.4.0
        id: build-image
        with:
          context: ${{ inputs.docker_context }}
          file: ${{ inputs.dockerfile_path }}/Dockerfile
          push: true
          tags: ${{ env.AZURE_REG_URL }}/${{ inputs.image }}:${{ inputs.tag }}

      - name: Generate Artifact Attestation
        uses: actions/attest-build-provenance@ef244123eb79f2f7a7e75d99086184180e6d0018 # v1.4.4
        with:
          subject-name: ${{ env.AZURE_REG_URL }}/${{ inputs.image }}
          subject-digest: '${{steps.build-image.outputs.digest}}'
          push-to-registry: true

      - name: Add End of Life Annotation
        run: |
          #get EOL date one month from now
          EOL_DATE=$(date -u -d "+1 month" +"%Y-%m-%dT%H:%M:%SZ")

          oras attach --artifact-type "application/vnd.microsoft.artifact.lifecycle" \
            --annotation "vnd.microsoft.artifact.lifecycle.end-of-life.date=$EOL_DATE" \
            $AZURE_REG_URL/${{ inputs.image }}@${{steps.build-image.outputs.digest}}