name: Release Images

on:
  schedule:
    - cron: '0 0 1 * *' # first of the month at midnight

permissions:
  id-token: write # This is required for requesting the JWT
  attestations: write
  packages: write
  contents: write # required for PR creation
  pull-requests: write # required for PR creation

jobs:
  test_all_images:
    name: Test All Images
    uses: ./.github/workflows/_test_all_images.yml

  increment_public_tag:
    name: Increment Public Tags
    needs: test_all_images
    runs-on: ubuntu-latest
    outputs:
      HELLOWORLD_ACI_VERSION: ${{ steps.increment.outputs.HELLOWORLD_ACI_VERSION }}
      HELLOWORLD_AKS_VERSION: ${{ steps.increment.outputs.HELLOWORLD_AKS_VERSION }}
      KAFKA_VERSION: ${{ steps.increment.outputs.KAFKA_VERSION }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Increment Tags
        id: increment
        run: |
          # File to store the values
          FILE="tags.json"

          # Read the current value -- last in the array
          CURR_HELLOWORLD_ACI_VER=$(jq -r '.["aci/helloworld"] | .[-1]' "$FILE")
          CURR_HELLOWORLD_AKS_VER=$(jq -r '.["aks/helloworld"] | .[-1]' "$FILE")
          CURR_KAFKA_VER=$(jq -r '.["kafka"] | .[-1]' "$FILE")

          # increment the patch version
          NEXT_HELLOWORLD_ACI_VER=$(echo $CURR_HELLOWORLD_ACI_VER | awk -F. '{$NF+=1; print $1"."$2"."$3}')
          NEXT_HELLOWORLD_AKS_VER=$(echo $CURR_HELLOWORLD_AKS_VER | awk -F. '{$NF+=1; print $1"."$2"."$3}')
          NEXT_KAFKA_VER=$(echo $CURR_KAFKA_VER | awk -F. '{$NF+=1; print $1"."$2"."$3}')

          # set the output for the new public build versions
          echo "HELLOWORLD_ACI_VERSION=$NEXT_HELLOWORLD_ACI_VER" >> $GITHUB_OUTPUT
          echo "HELLOWORLD_AKS_VERSION=$NEXT_HELLOWORLD_AKS_VER" >> $GITHUB_OUTPUT
          echo "KAFKA_VERSION=$NEXT_KAFKA_VER" >> $GITHUB_OUTPUT

          # store the updated values back to the file
          jq '.["aci/helloworld"] += ["'$NEXT_HELLOWORLD_ACI_VER'"]' "$FILE" > tmp.json && mv tmp.json "$FILE"
          jq '.["aks/helloworld"] += ["'$NEXT_HELLOWORLD_AKS_VER'"]' "$FILE" > tmp.json && mv tmp.json "$FILE"
          jq '.["kafka"] += ["'$NEXT_KAFKA_VER'"]' "$FILE" > tmp.json && mv tmp.json "$FILE"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: Update Image Tags for Public Release
          branch: update_image_tags
          delete-branch: true
          title: 'Update Image Tags for Public Release'
          body: |
            Update Image Tags for Public Release
            - Auto-generated by [update_image_tags][1]

            [1]: https://github.com/peter-evans/create-pull-request
          assignees: hgarvison # To-Do: update once we transfer ownership
          team-reviewers: |
            microsoft/accct

  release_all_images:
    name: Build and Push Docker Images
    needs: [test_all_images, increment_public_tag]
    uses: ./.github/workflows/_release_image.yml
    secrets: inherit
    if: github.event_name == 'schedule'
    strategy:
      matrix:
        image: ["aci/helloworld", "aks/helloworld", "kafka/consumer", "kafka/producer"]
        include:
          - image: "aci/helloworld"
            image_tag: ${{ needs.increment_public_tag.outputs.HELLOWORLD_ACI_VERSION }}
          - image: "aks/helloworld"
            image_tag: ${{ needs.increment_public_tag.outputs.HELLOWORLD_AKS_VERSION }}
          - image: "kafka/consumer"
            image_tag: ${{ needs.increment_public_tag.outputs.KAFKA_VERSION }}
          - image: "kafka/producer"
            image_tag: ${{ needs.increment_public_tag.outputs.KAFKA_VERSION }}
    with:
      image: ${{ matrix.image }}
      tag: ${{ matrix.image_tag }}
      repo_type: 'public'

